export const GET_DATA_PROGRESS="GET_DATA_PROGRESS";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_ERROR="GET_DATA_ERROR";

export const POST_DATA_PROGRESS="POST_DATA_PROGRESS";
export const POST_DATA_SUCCEESS="POST_DATA_SUCCEESS";
export const POST_DATA_ERROR="POST_DATA_ERROR";


